name: SpacePark Workflow
on: [push]
jobs:
  
  build:
    runs-on: windows-latest
    name: build job
  
    steps:
    - uses: actions@checkout@v2
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 5.0.x
    - run: dotnet build