name: SpacePark Workflow
on: [push]
jobs:
  
  build:
    runs-on: windows-latest
    name: build job
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 5.0.x
    - name: Build Project
      run: dotnet build .\Source\SpacePark\
    - name: Run Space Tests
      run: dotnet test .\Source\SpaceTests\